version: "0.0.1"
debug: true
croncrawler: "0 */2 * * * *"

sitesconfig: ["fantasysphere.yml","ultrajeux.yml","micromania.yml","parkage.yml","lequotidiendugeek.yml","fantastik.yml","lerepairedudragon.yml"]
# sitesconfig: ["fnac.yml","outpostbrussels.yml"]
# sitesconfig: ["lerepairedudragon.yml"]
