name: "fantastik"
country: "FR"
currency: "EUR"
stock:
  regex: <span id="availability_value" class="label (label-success)">
  type: "bool"
price: 
  regex: <span id="our_price_display" class="price" itemprop="price" content="([0-9\.]*)"
  type: "string"

urls:

  "One piece TCG Display OP02 ENG":
    language: "ENG"
    url: "https://www.fantastik.fr/jeux-de-cartes/23267-boite-complete-booster-one-piece-card-game-anglais-paramount-war-op-02.html"
    
  "One piece TCG Display OP03 ENG":
    language: "ENG"
    url: "https://www.fantastik.fr/jeux-de-cartes/24653-boite-complete-booster-one-piece-card-game-anglais-pillars-of-strength-op-03.html"
    
    
  "One piece TCG Starter ST06 ENG":
    language: "ENG"
    url: "https://www.fantastik.fr/jeux-de-cartes/23265-starter-deck-one-piece-card-game-anglais-absolute-justice-st06-100323-811039039127.html"
    
  "One piece TCG Starter ST07 ENG":
    language: "ENG"
    url: "https://www.fantastik.fr/jeux-de-cartes/23266-starter-deck-one-piece-card-game-anglais-big-mom-pirates-st07.html"
    
  "One piece TCG Booster OP03 ENG":
    language: "ENG"
    url: "https://www.fantastik.fr/jeux-de-cartes/24652-booster-one-piece-card-game-anglais-pillars-of-strength-op-03.html"
