name: "UltraJeux"
country: "FR"
currency: "EUR"
stock:
  regex: <input type="submit" value="(Ajouter)">
  type: "bool"
price: 
  regex: <span class="prix">([0-9,]*).*</span>
  type: "string"

urls:
  "One piece TCG Display OP01":
    language: "ENG"
    url: "https://www.ultrajeux.com/produit-20576-boite-de-24-boosters-romance-dawn-op01-0811039038205.html"
  "One piece TCG Display OP02":
    language: "ENG"
    url: "https://www.ultrajeux.com/produit-21124-boite-de-24-boosters-paramount-war-op02-.html"

